### ISSUE TITLE
go get error

### ISSUE THREAD

**Issue by myimilo** [crawlerclub/crawler#7]
$ go get -u github.com/crawlerclub/crawler
package crawler.club/crawler/rss: unrecognized import path "crawler.club/crawler/rss" (parse https://crawler.club/crawler/rss?go-get=1: no go-import meta tags ())
package crawler.club/crawler/version: unrecognized import path "crawler.club/crawler/version" (parse https://crawler.club/crawler/version?go-get=1: no go-import meta tags ())

**Comment by liuzl** [comment]
Thanks for pointing out

1. Try to `go get` from `crawler.club/crawler`.
2. `crawler.club/crawler/rss` and `crawler.club/crawler/version` were not set properly, I just fixed them.

You can try now, thanks again.
